[package]
name = "input-validation-fuzz"
version = "0.0.0"
publish = false
edition = "2021"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.input-validation]
path = ".."

# Additional dependencies for fuzz targets (main crate provides most)
jsonwebtoken = "9.3"
proptest = "1.5"
quickcheck = "1.0"
arbitrary = "1.4"

[profile.release]
debug = 1

[[bin]]
name = "fuzz_target_1"
path = "fuzz_targets/fuzz_target_1.rs"
test = false
doc = false

[[bin]]
name = "scim_filter"
path = "fuzz_targets/scim_filter.rs"
test = false
doc = false

[[bin]]
name = "oauth_params"
path = "fuzz_targets/oauth_params.rs"
test = false
doc = false

[[bin]]
name = "jwt_tokens"
path = "fuzz_targets/jwt_tokens.rs"
test = false
doc = false

[[bin]]
name = "input_validation"
path = "fuzz_targets/input_validation.rs"
test = false
doc = false
