apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "auth-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "auth-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "auth-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: ENVIRONMENT
              value: {{ .Values.config.environment | quote }}
            - name: RUST_LOG
              value: {{ .Values.config.logLevel | quote }}
            - name: BIND_ADDR
              value: {{ .Values.config.bindAddr | quote }}
            - name: TOKEN_EXPIRY_SECONDS
              value: {{ .Values.config.tokenExpirySeconds | quote }}
            - name: RATE_LIMIT_REQUESTS_PER_MINUTE
              value: {{ .Values.config.rateLimitRequestsPerMinute | quote }}
            - name: ALLOWED_ORIGINS
              value: {{ .Values.config.allowedOrigins | quote }}
            - name: JAEGER_ENDPOINT
              value: {{ .Values.config.jaegerEndpoint | quote }}
            - name: REDIS_URL
              value: "redis://{{ include "auth-service.fullname" . }}-redis-master:6379"
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-service.fullname" . }}-secret
                  key: jwt-secret
            - name: CLIENT_CREDENTIALS
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-service.fullname" . }}-secret
                  key: client-credentials
            - name: REQUEST_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-service.fullname" . }}-secret
                  key: request-signing-secret
            {{- if .Values.config.googleClientId }}
            - name: GOOGLE_CLIENT_ID
              value: {{ .Values.config.googleClientId | quote }}
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "auth-service.fullname" . }}-secret
                  key: google-client-secret
            - name: GOOGLE_REDIRECT_URI
              value: {{ .Values.config.googleRedirectUri | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: http
            initialDelaySeconds: {{ .Values.healthCheck.initialDelaySeconds }}
            periodSeconds: {{ .Values.healthCheck.periodSeconds }}
            timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
            failureThreshold: {{ .Values.healthCheck.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.healthCheck.path }}
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: {{ .Values.healthCheck.timeoutSeconds }}
            failureThreshold: 3
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: cache
              mountPath: /app/cache
      volumes:
        - name: tmp
          emptyDir: {}
        - name: cache
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
