{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "auth-service.fullname" . }}-external-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: security
spec:
  refreshInterval: {{ .Values.externalSecrets.refreshInterval | default "15m" }}
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind | default "SecretStore" }}
  target:
    name: {{ include "auth-service.fullname" . }}-secret
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          {{- include "auth-service.labels" . | nindent 10 }}
          app.kubernetes.io/managed-by: external-secrets
        annotations:
          external-secrets.io/last-refresh: "{{`{{ now | unixEpoch }}`}}"
          {{- with .Values.externalSecrets.annotations }}
          {{- toYaml . | nindent 10 }}
          {{- end }}
  data:
    {{- range .Values.externalSecrets.secrets }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property }}
        {{- end }}
        {{- if .remoteRef.version }}
        version: {{ .remoteRef.version }}
        {{- end }}
    {{- end }}
{{- end }}