{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "auth-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "auth-service.fullname" . }}
  minReplicas: {{ .Values.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.customMetrics }}
    {{- range .Values.autoscaling.customMetrics }}
    - type: {{ .type }}
      {{- if eq .type "Pods" }}
      pods:
        metric:
          name: {{ .metric.name }}
          {{- if .metric.selector }}
          selector:
            {{- toYaml .metric.selector | nindent 12 }}
          {{- end }}
        target:
          type: {{ .target.type }}
          {{- if .target.averageValue }}
          averageValue: {{ .target.averageValue }}
          {{- end }}
          {{- if .target.value }}
          value: {{ .target.value }}
          {{- end }}
      {{- else if eq .type "Object" }}
      object:
        metric:
          name: {{ .metric.name }}
          {{- if .metric.selector }}
          selector:
            {{- toYaml .metric.selector | nindent 12 }}
          {{- end }}
        describedObject:
          apiVersion: {{ .describedObject.apiVersion }}
          kind: {{ .describedObject.kind }}
          name: {{ .describedObject.name }}
        target:
          type: {{ .target.type }}
          {{- if .target.averageValue }}
          averageValue: {{ .target.averageValue }}
          {{- end }}
          {{- if .target.value }}
          value: {{ .target.value }}
          {{- end }}
      {{- else if eq .type "External" }}
      external:
        metric:
          name: {{ .metric.name }}
          {{- if .metric.selector }}
          selector:
            {{- toYaml .metric.selector | nindent 12 }}
          {{- end }}
        target:
          type: {{ .target.type }}
          {{- if .target.averageValue }}
          averageValue: {{ .target.averageValue }}
          {{- end }}
          {{- if .target.value }}
          value: {{ .target.value }}
          {{- end }}
      {{- end }}
    {{- end }}
    {{- end }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleDown.stabilizationWindowSeconds | default 300 }}
      policies:
      - type: Percent
        value: {{ .Values.autoscaling.behavior.scaleDown.percentPolicy | default 50 }}
        periodSeconds: {{ .Values.autoscaling.behavior.scaleDown.periodSeconds | default 60 }}
      - type: Pods
        value: {{ .Values.autoscaling.behavior.scaleDown.podsPolicy | default 2 }}
        periodSeconds: {{ .Values.autoscaling.behavior.scaleDown.periodSeconds | default 60 }}
      selectPolicy: {{ .Values.autoscaling.behavior.scaleDown.selectPolicy | default "Min" }}
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.autoscaling.behavior.scaleUp.stabilizationWindowSeconds | default 60 }}
      policies:
      - type: Percent
        value: {{ .Values.autoscaling.behavior.scaleUp.percentPolicy | default 100 }}
        periodSeconds: {{ .Values.autoscaling.behavior.scaleUp.periodSeconds | default 60 }}
      - type: Pods
        value: {{ .Values.autoscaling.behavior.scaleUp.podsPolicy | default 4 }}
        periodSeconds: {{ .Values.autoscaling.behavior.scaleUp.periodSeconds | default 60 }}
      selectPolicy: {{ .Values.autoscaling.behavior.scaleUp.selectPolicy | default "Max" }}
{{- end }}