{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "auth-service.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: security
spec:
  podSelector:
    matchLabels:
      {{- include "auth-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    {{- range .Values.networkPolicy.ingress }}
    - {{- if .from }}
      from:
        {{- range .from }}
        - {{- if .namespaceSelector }}
          namespaceSelector:
            {{- toYaml .namespaceSelector | nindent 12 }}
          {{- end }}
          {{- if .podSelector }}
          podSelector:
            {{- toYaml .podSelector | nindent 12 }}
          {{- end }}
          {{- if .ipBlock }}
          ipBlock:
            {{- toYaml .ipBlock | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if .ports }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
        {{- end }}
      {{- end }}
    {{- end }}
  egress:
    {{- range .Values.networkPolicy.egress }}
    - {{- if .to }}
      to:
        {{- range .to }}
        - {{- if .namespaceSelector }}
          namespaceSelector:
            {{- toYaml .namespaceSelector | nindent 12 }}
          {{- end }}
          {{- if .podSelector }}
          podSelector:
            {{- toYaml .podSelector | nindent 12 }}
          {{- end }}
          {{- if .ipBlock }}
          ipBlock:
            {{- toYaml .ipBlock | nindent 12 }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- if .ports }}
      ports:
        {{- range .ports }}
        - protocol: {{ .protocol | default "TCP" }}
          port: {{ .port }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}