{{- if not .Values.externalSecrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "auth-service.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: security
  annotations:
    # Warning annotation for production deployments
    {{- if eq .Values.config.environment "production" }}
    security.rust-security.io/warning: "Using static secrets in production is not recommended. Consider using ExternalSecrets."
    {{- end }}
type: Opaque
data:
  # Base64 encoded secret values
  jwt-secret: {{ .Values.secrets.jwtSecret | b64enc | quote }}
  client-credentials: {{ .Values.secrets.clientCredentials | b64enc | quote }}
  request-signing-secret: {{ .Values.secrets.requestSigningSecret | b64enc | quote }}
  {{- if .Values.secrets.googleClientSecret }}
  google-client-secret: {{ .Values.secrets.googleClientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.redisPassword }}
  redis-password: {{ .Values.secrets.redisPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.secrets.databaseUrl }}
  database-url: {{ .Values.secrets.databaseUrl | b64enc | quote }}
  {{- end }}
{{- end }}