# Clippy configuration for rust-security project

# Allow unwrap in tests (security testing often needs this)
allow-unwrap-in-tests = true
allow-dbg-in-tests = true

# Performance optimizations
arithmetic-side-effects-allowed = ["core::num::*"]

# Allow some complex types in security APIs
type-complexity-threshold = 300

# Allow cognitive complexity for security algorithms
cognitive-complexity-threshold = 25

# Documentation settings
doc-valid-idents = ["..*"]
missing-docs-in-crate-items = false

# Allow controlled dependency version conflicts
msrv = "1.80"

# Security-specific disallowed methods
disallowed-methods = [
    { path = "rand::thread_rng", reason = "Use cryptographically secure random instead" },
    { path = "rand::random", reason = "Use cryptographically secure random instead" },
]
