edition = "2021"
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Max"
max_width = 100
hard_tabs = false
tab_spaces = 4
fn_params_layout = "Tall"
reorder_imports = true
reorder_modules = true
remove_nested_parens = true