# Rust formatting configuration
# This ensures consistent formatting across the project

# Edition and stability  
edition = "2021"
unstable_features = false

# General formatting
max_width = 100
hard_tabs = false
tab_spaces = 4

# Line endings
newline_style = "Unix"

# Import organization
imports_granularity = "Crate"
group_imports = "StdExternalCrate"

# Function signatures
fn_args_layout = "Tall"
fn_single_line = false

# Control flow
control_brace_style = "AlwaysSameLine"

# Comments and strings
comment_width = 100
normalize_comments = true
wrap_comments = true

# Error handling
format_code_in_doc_comments = true

# Trailing commas and semicolons
trailing_comma = "Vertical"
trailing_semicolon = true

# Spacing and alignment
spaces_around_ranges = false
type_punctuation_density = "Wide"

# Match expressions
match_block_trailing_comma = true
match_arm_blocks = true

# Arrays and structures
array_width = 60
struct_lit_width = 18
chain_width = 60

# Miscellaneous
remove_nested_parens = true
use_small_heuristics = "Default"