edition = "2021"
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
use_small_heuristics = "Max"
max_width = 100
hard_tabs = false
tab_spaces = 4
fn_args_layout = "Tall"
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
trailing_semicolon = true
trailing_comma = "Vertical"
match_block_trailing_comma = false
blank_lines_upper_bound = 1
blank_lines_lower_bound = 0
reorder_imports = true
reorder_modules = true
remove_nested_parens = true
group_imports = "StdExternalCrate"
imports_indent = "Visual"
imports_layout = "Mixed"
merge_imports = false
wrap_comments = false
format_code_in_doc_comments = true
normalize_comments = false
normalize_doc_attributes = false
license_template_path = ""
format_strings = false
format_macro_matchers = true
format_macro_bodies = true
empty_item_single_line = true
struct_lit_single_line = true
fn_single_line = false
where_single_line = false
imports_granularity = "Crate"