# Rust formatting configuration
# This ensures consistent formatting across the project
# Only uses stable rustfmt features

# Edition and general formatting
edition = "2021"
max_width = 100
hard_tabs = false
tab_spaces = 4

# Line endings
newline_style = "Unix"

# Function signatures  
fn_params_layout = "Tall"

# Arrays and structures
array_width = 60
struct_lit_width = 18
chain_width = 60

# Miscellaneous
remove_nested_parens = true
use_small_heuristics = "Default"