[workspace.package]
edition = "2021"
rust-version = "1.75"

[workspace]
members = [
    "auth-core",
    "auth-service",
    "policy-service",
    "common",
    "api-contracts",
    "compliance-tools",
    "examples/axum-integration-example"
]

exclude = [
    "red-team-exercises",
    "user-portal",
    "security-platform",
    "input-validation",
    "chaos-engineering",
    "security-testing",
    "tests"
]

resolver = "2"

[workspace.lints]
rust.unused_crate_dependencies = "warn"
rust.unused_imports = "warn"
rust.dead_code = "warn"
rust.unsafe_code = "forbid"
clippy.all = "warn"
clippy.pedantic = "warn"
clippy.cargo = "warn"
clippy.nursery = "warn"

[workspace.dependencies]
# Core async runtime
tokio = { version = "1.41", features = ["full"] }
axum = { version = "0.7", features = ["macros"] }
tower = { version = "0.5", features = ["util"] }
hyper = { version = "1.5" }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "2.0"

# Cryptography
jsonwebtoken = "9.3"
rand = "0.8"
sha2 = "0.10"
sha1 = "0.10"
aes = "0.8"
aes-gcm = "0.10"

# Database
sqlx = { version = "0.8", features = ["postgres", "sqlite", "chrono", "uuid", "migrate", "macros", "runtime-tokio-rustls"], default-features = false }
deadpool = "0.12"

# Redis
redis = { version = "0.27", features = ["aio", "connection-manager", "tokio-comp"] }
deadpool-redis = "0.18"

# Monitoring
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
prometheus = "0.14"

# UUID
uuid = { version = "1.11", features = ["v4", "serde"] }

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# HTTP client
reqwest = { version = "0.12", features = ["json"] }

# Configuration
config = "0.14"

# Validation - Updated to fix idna vulnerability
validator = { version = "0.20", features = ["derive"] }

# CLI
clap = { version = "4.5", features = ["derive"] }

# Additional common dependencies
async-trait = "0.1"
headers = "0.4"
base64 = "0.21"
bytes = "1.8"
constant_time_eq = "0.3"
dashmap = "6.1"
data-encoding = "2.6"
dotenvy = "0.15"
envy = "0.4"
futures = "0.3"
hex = "0.4"
hmac = "0.12"
once_cell = "1.20"
secrecy = "0.10"
subtle = "2.6"
zeroize = "1.8"

# Web/HTTP additional
http = "1.1"
http-body-util = "0.1"
tower-http = { version = "0.6", features = ["cors", "fs", "trace", "request-id", "limit", "timeout"] }
urlencoding = "2.1"
url = "2.5"

# Policy engine
cedar-policy = "4.2"

# API documentation
utoipa = { version = "5.1", features = ["axum_extras"] }

# Crypto additional
argon2 = "0.5"
bcrypt = "0.16"
chacha20poly1305 = "0.10"
ring = "0.17"
rustls-pemfile = "2.2"
ed25519-dalek = "2.1"
x25519-dalek = "2.0"
p256 = "0.13"
p384 = "0.13"

# Development/Testing - Keep wiremock at 0.6 for now
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.5"
quickcheck = "1.0"
quickcheck_macros = "1.0"
tempfile = "3.13"
pretty_assertions = "1.4"
tokio-test = "0.4"
wiremock = "0.6"
arbitrary = "1.4"

# Storage/DB additional
bb8 = "0.8"
bb8-redis = "0.16"
rmp-serde = "1.3"
bincode = "1.3"

# ML/Advanced features
smartcore = "0.3"
ndarray = "0.16"
nalgebra = "0.33"

# Post-quantum crypto
pqcrypto-mlkem = "0.1"
pqcrypto-mldsa = "0.1"

# Cloud integrations
aws-config = "1.5"
aws-sdk-secretsmanager = "1.48"
vaultrs = "0.7"

# Monitoring/telemetry
opentelemetry = "0.22"
opentelemetry-jaeger = "0.22"
opentelemetry_sdk = "0.22"
tracing-opentelemetry = "0.22"
tokio-metrics = "0.3"
metrics = "0.24"
metrics-prometheus = "0.8"

# Templating
handlebars = "6.2"
tera = "1.20"

# Email
lettre = "0.11"

# Performance
mimalloc = "0.1"
rayon = "1.10"

# Compression
lz4_flex = "0.11"

# Filesystem/memory mapping
memmap2 = "0.9"
walkdir = "2.5"

# Search/pattern matching
aho-corasick = "1.1"
regex = "1.11"
fancy-regex = "0.13"

# Networking/geo
ipnet = "2.10"
geo = "0.28"
geoutils = "0.5"

# Data structures
indexmap = "2.6"
bloomfilter = "1.0"
petgraph = "0.6"

# Async/concurrency
flume = "0.11"
crossbeam = "0.8"

# Statistics
statrs = "0.17"

# Time handling
time = "0.3"

# Certificates/PKI
x509-cert = "0.2"
pkcs8 = "0.10"
der = "0.7"
rcgen = "0.13"

# Config formats
toml = "0.8"
serde_yaml = "0.9"

# Documentation
utoipa-swagger-ui = "8.1"

# Web server
axum-server = "0.7"

# Policy engine core
cedar-policy-core = "4.2"

# Random number generation
fastrand = "2.2"
getrandom = { version = "0.2", features = ["std"] }

# Lazy initialization
lazy_static = "1.5"

# System info
num_cpus = "1.16"

# Probabilistic data structures
probabilistic-collections = "0.7"

# Profiling - Removed due to RUSTSEC-2024-0408 memory safety vulnerability
# pprof2 = "0.14.0"  # Use alternative profiling tools like flamegraph or perf

# TypeScript (placeholder, not a real crate - commenting out)
# tsc = "0.1"

# Additional network/TLS dependencies
ipnetwork = "0.20"
opentelemetry-otlp = "0.15"
x509-parser = "0.17"
rustls = "0.23"
webpki-roots = "0.26"

# DNS resolution - security-focused replacement for trust-dns
hickory-resolver = "0.24"

[profile.dev]
opt-level = 1
debug = true
incremental = true
split-debuginfo = "unpacked"

[profile.release]
opt-level = 3
debug = false
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.test]
opt-level = 1
debug = true

[profile.bench]
opt-level = 3
debug = false
lto = true

# Feature organization
[workspace.metadata.features]
core = [
    "oauth2-client-credentials",
    "jwt-tokens",
    "memory-store",
    "rate-limiting-basic"
]

standard = [
    "oauth2-authorization-code",
    "oauth2-refresh-tokens",
    "postgresql-store",
    "redis-sessions",
    "mfa-totp",
    "prometheus-metrics"
]

enterprise = [
    "mfa-webauthn",
    "saml-federation",
    "soar-integration",
    "threat-detection",
    "multi-tenancy",
    "audit-compliance"
]

experimental = [
    "post-quantum-crypto",
    "ml-threat-detection",
    "chaos-engineering",
    "zero-trust-networking"
]


# Security metadata for supply chain verification
[workspace.metadata.security]
audit_policy = "strict"
vulnerability_tolerance = "none"
dependency_review_required = true
security_contact = "security@company.com"
