[workspace]
resolver = "2"
members = [
    "common",
    "auth-service", 
    "policy-service",
    "examples/axum-integration-example",
    "examples/simple-auth-client",
    "compliance-tools",
    "red-team-exercises",
    "tests",
    "input-validation",
    "chaos-engineering",
    "security-testing",
]


[workspace.dependencies]
# Core runtime dependencies
tokio = { version = "1.0", features = ["rt-multi-thread", "macros", "signal", "sync", "time", "fs"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "2.0"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }
chrono = { version = "0.4.22", features = ["serde"] }  # Version >= 0.4.20 to avoid RUSTSEC-2020-0159
uuid = { version = "1.0", features = ["v4", "serde"] }

# HTTP and networking
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
http = "1.0"
bytes = "1.0"
url = "2.5"
urlencoding = "2.1"
fastrand = "2.1"
libfuzzer-sys = "0.4"
clap = { version = "4.5", features = ["derive"] }

# Web framework dependencies
axum = { version = "0.7", features = ["macros"] }
axum-server = { version = "0.7", features = ["tls-rustls"] }
hyper = { version = "1.0", features = ["full"] }
tower = { version = "0.5", features = ["limit"] }
tower-http = { version = "0.6", features = ["trace", "request-id", "cors", "limit", "timeout"] }

# Security and crypto (using latest secure versions)
rand = "0.8.5"  # Version >= 0.8 to avoid security issues
argon2 = "0.5"
jsonwebtoken = "9.0"
ring = "0.17"
aes-gcm = "0.10"
aes = "0.8"
chacha20poly1305 = "0.10"
hmac = "0.12"
sha1 = "0.10"
sha2 = "0.10"
data-encoding = "2.6"
base64 = "0.21"
hex = "0.4"
secrecy = "0.10"
constant_time_eq = "0.3"
zeroize = "1.7"
subtle = "2.5"
rcgen = "0.13"

# Data validation and serialization
validator = { version = "0.20", features = ["derive"] }
rmp-serde = "1.1"
bincode = "1.3"
toml = "0.8"
serde_yaml = "0.9"

# Redis with secure TLS
redis = { version = "0.32", features = ["tokio-comp", "aio", "connection-manager"] }
bb8 = "0.8"
bb8-redis = "0.24"
deadpool = "0.12"
deadpool-redis = "0.14"

# Documentation and OpenAPI
utoipa = { version = "4", features = ["axum_extras", "uuid"] }
utoipa-swagger-ui = { version = "6", features = ["axum"] }

# Configuration
dotenvy = "0.15"
envy = "0.4"
once_cell = "1.0"

# Async utilities
async-trait = "0.1"
flume = "0.11"
crossbeam = "0.8"

# Performance and metrics
prometheus = "0.14"
tokio-metrics = "0.3"
criterion = { version = "0.5", features = ["html_reports"] }
pprof = { version = "0.14", features = ["criterion", "flamegraph"] }
dashmap = "6.1"
num_cpus = "1.16"
rayon = "1.8"

# Observability
opentelemetry = "0.21"
opentelemetry-jaeger = "0.20"
tracing-opentelemetry = "0.22"
opentelemetry_sdk = { version = "0.21", features = ["rt-tokio"] }

# Memory allocators
mimalloc = "0.1"
jemalloc = "0.3"

# Pattern matching and text processing
regex = "1.0"
fancy-regex = "0.13"
aho-corasick = "1.1"

# Collections and data structures
indexmap = { version = "2.0", features = ["serde"] }
petgraph = { version = "0.6", features = ["serde"] }
bloomfilter = "1.0"
probabilistic-collections = "0.7"
lazy_static = "1.4"

# Compression
lz4_flex = "0.11"
memmap2 = "0.9"

# Network analysis
ipnet = "2.9"
geo = { version = "0.28", features = ["serde"] }
geoutils = "0.5"

# Time handling
time = { version = "0.3", features = ["parsing", "formatting", "serde"] }

# Machine Learning and Analytics
smartcore = { version = "0.3", features = ["serde"] }
candle-core = "0.8"
candle-nn = "0.8"
candle-transformers = "0.8"
ndarray = { version = "0.16", features = ["serde"] }
nalgebra = { version = "0.32", features = ["serde"] }
statrs = "0.17"
tsc = "0.1"

# Post-Quantum Cryptography (updated to maintained alternatives)
pqcrypto-mlkem = "0.1"  # Replacement for pqcrypto-kyber
pqcrypto-mldsa = "0.1"  # Replacement for pqcrypto-dilithium
p256 = "0.13"
p384 = "0.13"
ed25519-dalek = "2.1"
x25519-dalek = "2.0"
x509-cert = "0.2"
pkcs8 = "0.10"
der = "0.7"

# External services
vaultrs = "0.7"
aws-config = "1.0"
aws-sdk-secretsmanager = "1.0"

# SOAR dependencies (removed mysql to avoid RSA vulnerability)
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "sqlite", "uuid", "chrono", "json", "migrate", "macros"], default-features = false }
handlebars = "6.1"
lettre = { version = "0.11", features = ["smtp-transport", "pool", "hostname", "builder", "rustls-tls"], default-features = false }
tera = "1.20"
walkdir = "2.5"

# Policy engine
cedar-policy = "3.0"
cedar-policy-core = "4.5.1"

# Testing dependencies
proptest = "1.4"
quickcheck = "1.0"
quickcheck_macros = "1.0"
tokio-test = "0.4"
tempfile = "3.10"
wiremock = "0.6"
arbitrary = { version = "1.3", features = ["derive"] }
getrandom = "0.2"
simd = "0.2"

# Additional dependencies for examples and red-team exercises
bcrypt = "0.15"
metrics = "0.22"
metrics-prometheus = "0.6"
http-body-util = "0.1"
futures = "0.3"

# Workspace-level lints configuration
[workspace.lints.rust]
unsafe_code = "warn"
missing_docs = "warn"
rust_2018_idioms = { level = "warn", priority = -1 }
unreachable_pub = "warn"
# Security-focused lints
non_ascii_idents = "deny"
absolute_paths_not_starting_with_crate = "warn"
deprecated_in_future = "warn"
meta_variable_misuse = "deny"
# Performance lints
single_use_lifetimes = "warn"
trivial_casts = "warn"
trivial_numeric_casts = "warn"
unused_extern_crates = "warn"
unused_import_braces = "warn"
unused_qualifications = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }
# Security-focused clippy lints
# integer_overflow = "deny" # Not a valid clippy lint
panic = "deny"
unwrap_used = "deny"
expect_used = "warn"
indexing_slicing = "warn"
# Crypto and security patterns
todo = "warn"
unimplemented = "deny"
# Performance lints
inefficient_to_string = "warn"
large_enum_variant = "warn"
large_stack_arrays = "warn"
# Allow some common patterns but keep most strict
module_name_repetitions = "allow"
must_use_candidate = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
multiple_crate_versions = "allow"
too_many_lines = "allow"  # Some security functions are legitimately long
similar_names = "allow"   # Common in crypto code (e.g., pk, sk)
# Security-critical: warn on potential timing attacks
float_cmp = "warn"
float_cmp_const = "warn"

# Workspace-level profile configuration
[profile.dev]
opt-level = 0
debug = 1  # Line tables only, faster builds
debug-assertions = true
overflow-checks = true
lto = false
panic = 'unwind'
incremental = true
codegen-units = 512  # More parallelism for faster incremental builds
rpath = false
split-debuginfo = "packed"  # Faster debug info on macOS

[profile.release]
opt-level = 3
debug = false
debug-assertions = false
overflow-checks = false
lto = "thin"
panic = 'unwind'
incremental = false
codegen-units = 16
rpath = false
strip = true

[profile.release-with-debug]
inherits = "release"
debug = true
strip = false

[profile.bench]
inherits = "release"
debug = true

[profile.test]
opt-level = 0
debug = 1
debug-assertions = true
overflow-checks = true
lto = false
incremental = true
codegen-units = 512
rpath = false
split-debuginfo = "packed"

# Fast builds for dev dependencies
[profile.dev.build-override]
opt-level = 3
codegen-units = 1

# Optimize build scripts and proc macros
[profile.dev.package."proc-macro2"]
opt-level = 3
[profile.dev.package."quote"]
opt-level = 3
[profile.dev.package."syn"]
opt-level = 3
# Kubernetes dependencies
kube = "0.90"
k8s-openapi = { version = "0.22", features = ["latest"] }

# Additional security testing dependencies  
jsonwebtoken = "9.0"
