[workspace]
members = [
    "auth-core",
    "auth-service", 
    "policy-service",
]

resolver = "2"

[workspace.lints]
rust.unused_crate_dependencies = "warn"
rust.unused_imports = "warn" 
rust.dead_code = "warn"

[workspace.dependencies]
# Core async runtime
tokio = { version = "1.0", features = ["full"] }
axum = { version = "0.7", features = ["macros"] }
tower = { version = "0.4" }
hyper = { version = "1.0" }

# Serialization
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

# Error handling
anyhow = "1.0"
thiserror = "1.0"

# Cryptography
jsonwebtoken = "9.0"
rand = "0.8"
sha2 = "0.10"
sha1 = "0.10"
aes = "0.8"
aes-gcm = "0.10"

# Database
sqlx = { version = "0.8", features = ["postgres", "sqlite", "chrono", "uuid", "migrate", "macros", "runtime-tokio-rustls"], default-features = false }
deadpool = "0.12"

# Redis
redis = { version = "0.26", features = ["aio", "connection-manager"] }
deadpool-redis = "0.18"

# Monitoring
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
prometheus = "0.14"

# UUID
uuid = { version = "1.0", features = ["v4", "serde"] }

# Time handling
chrono = { version = "0.4", features = ["serde"] }

# HTTP client
reqwest = { version = "0.12", features = ["json"] }

# Configuration
config = "0.14"

# Validation
validator = { version = "0.19", features = ["derive"] }

# CLI
clap = { version = "4.0", features = ["derive"] }

# Additional common dependencies
async-trait = "0.1"
base64 = "0.22"
bytes = "1.0"
constant_time_eq = "0.3"
dashmap = "6.0"
data-encoding = "2.0"
dotenvy = "0.15"
envy = "0.4"
hex = "0.4"
hmac = "0.12"
lazy_static = "1.5"
num_cpus = "1.0"
once_cell = "1.21"
secrecy = "0.10"
subtle = "2.5"
zeroize = "1.8"

# Web/HTTP additional
http = "1.0"
tower-http = { version = "0.5", features = ["cors", "fs", "trace", "request-id", "limit", "timeout"] }
urlencoding = "2.1"
url = "2.5"

# Policy engine
cedar-policy = "4.0"

# API documentation
utoipa = { version = "5.0", features = ["axum_extras"] }

# Crypto additional  
argon2 = "0.5"
chacha20poly1305 = "0.10"
ring = "0.17"
rsa = "0.9"
x25519-dalek = "2.0"
ed25519-dalek = "2.1"
p256 = "0.13"
p384 = "0.13"

# Development/Testing
criterion = { version = "0.5", features = ["html_reports"] }
proptest = "1.0"
quickcheck = "1.0"
quickcheck_macros = "1.0"
tempfile = "3.0"
tokio-test = "0.4"
wiremock = "0.6"
arbitrary = "1.0"

# Storage/DB additional
bb8 = "0.8"
bb8-redis = "0.16"
rmp-serde = "1.0"
bincode = "1.0"

# ML/Advanced features
smartcore = "0.3"
ndarray = "0.16" 
nalgebra = "0.33"

# Post-quantum crypto
pqcrypto-mlkem = "0.1"
pqcrypto-mldsa = "0.1"

# Cloud integrations
aws-config = "1.0"
aws-sdk-secretsmanager = "1.0"
vaultrs = "0.7"

# Monitoring/telemetry
opentelemetry = "0.23"
opentelemetry-jaeger = "0.22"
opentelemetry_sdk = "0.23"
tracing-opentelemetry = "0.24"
tokio-metrics = "0.3"
metrics = "0.23"
metrics-prometheus = "0.7"
pprof = "0.15"

# Templating
handlebars = "6.0"
tera = "1.0"

# Email
lettre = "0.11"

# Performance
mimalloc = "0.1"
tikv-jemalloc-ctl = "0.5"
jemalloc-sys = "0.5"
rayon = "1.0"
packed_simd_2 = "0.3"

# Compression
lz4_flex = "0.11"

# Filesystem/memory mapping
memmap2 = "0.9"
walkdir = "2.0"

# Search/pattern matching
aho-corasick = "1.0"
fancy-regex = "0.13"
regex = "1.0"

# Networking/geo
ipnet = "2.0"
geo = "0.28"
geoutils = "0.5"

# Data structures  
indexmap = "2.0"
bloomfilter = "1.0"
probabilistic-collections = "0.7"
petgraph = "0.6"

# Async/concurrency
flume = "0.11"
crossbeam = "0.8"

# Statistics
statrs = "0.17"

# Time handling
time = "0.3"

# Certificates/PKI
x509-cert = "0.2"
pkcs8 = "0.10"
der = "0.7"
rcgen = "0.13"

# Config formats
toml = "0.8"
serde_yaml = "0.9"

# Fuzzing
libfuzzer-sys = "0.4"

# Documentation
# Duplicate removed - defined above
utoipa-swagger-ui = "8.0"

# Web server
axum-server = "0.7"

# Policy engine (duplicate removed - defined above)
cedar-policy-core = "4.0"

# TypeScript compiler
tsc = "0.1"

# Random number generation
fastrand = "2.0"
getrandom = { version = "0.3", features = ["std"] }

# WebAssembly/ML
candle-core = "0.7"
candle-nn = "0.7"
candle-transformers = "0.7"

[profile.dev]
# Faster builds for development
opt-level = 1
debug = true
incremental = true

[profile.release]
# Optimized for production
opt-level = 3
debug = false
lto = true
codegen-units = 1
panic = "abort"

[profile.test]
# Optimized for testing
opt-level = 1
debug = true

# Feature organization
[workspace.metadata.features]
# Core features - minimal OAuth functionality
core = [
    "oauth2-client-credentials",
    "jwt-tokens", 
    "memory-store",
    "rate-limiting-basic"
]

# Standard features - common enterprise needs
standard = [
    "oauth2-authorization-code",
    "oauth2-refresh-tokens", 
    "postgresql-store",
    "redis-sessions",
    "mfa-totp",
    "prometheus-metrics"
]

# Enterprise features - advanced security
enterprise = [
    "mfa-webauthn",
    "saml-federation",
    "soar-integration", 
    "threat-detection",
    "multi-tenancy",
    "audit-compliance"
]

# Experimental features
experimental = [
    "post-quantum-crypto",
    "ml-threat-detection",
    "chaos-engineering",
    "zero-trust-networking"
]

# Build profiles for different use cases
[workspace.metadata.profiles]

[workspace.metadata.profiles.minimal]
description = "Minimal OAuth server for development"
features = ["core"]
size_estimate = "< 10MB"
build_time = "< 2 minutes"

[workspace.metadata.profiles.production]
description = "Production-ready with monitoring"
features = ["core", "standard"]
size_estimate = "< 50MB"
build_time = "< 5 minutes"

[workspace.metadata.profiles.enterprise]
description = "Full enterprise feature set"
features = ["core", "standard", "enterprise"]
size_estimate = "< 150MB"
build_time = "< 15 minutes"