# Clippy configuration for security-focused linting
avoid-breaking-exported-api = false
msrv = "1.70.0"

disallowed-methods = [
    "std::ptr::read",
    "std::ptr::write",
    "std::mem::transmute",
    "std::slice::get_unchecked",
    "std::str::from_utf8_unchecked",
]

disallowed-types = [
    "md5::Md5",
    "sha1::Sha1",
]

cognitive-complexity-threshold = 30
type-complexity-threshold = 250

# Allow known dependency version conflicts that are difficult to resolve
# without breaking changes to the ecosystem
allow = [
    "multiple-crate-versions",
]
