# Enhanced cargo-deny configuration for supply chain security
# This configuration enforces strict security policies for dependencies

[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
]
all-features = true
no-default-features = false

[output]
feature-depth = 1

[advisories]
# Security advisory database configuration
db-path = "~/.cargo/advisory-db"
db-urls = [
    "https://github.com/rustsec/advisory-db",
    "https://github.com/github/advisory-database"
]

# Vulnerability severity levels that cause failure
vulnerability = "deny"
unmaintained = "warn"
yanked = "deny"
notice = "warn"
ignore = [
    # Add specific advisories to ignore (with justification)
    # Example: "RUSTSEC-2023-0001", # Justified: Not applicable to our use case
]

[licenses]
# License policy for supply chain compliance
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "0BSD",
    "Zlib",
    "MPL-2.0",
]

deny = [
    "GPL-2.0",
    "GPL-3.0",
    "AGPL-1.0",
    "AGPL-3.0",
    "LGPL-2.0",
    "LGPL-2.1",
    "LGPL-3.0",
    "CDDL-1.0",
    "CDDL-1.1",
    "EPL-1.0",
    "EPL-2.0",
    "EUPL-1.1",
    "EUPL-1.2",
    "SSPL-1.0",
    "BUSL-1.1",
]

copyleft = "deny"
allow-osi-fsf-free = "both"
default = "deny"
confidence-threshold = 0.8

[licenses.private]
# Allow licenses for internal/private use
ignore = false
registries = []

[bans]
# Banned crates and versions for security reasons
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"

deny = [
    # Cryptographic libraries with known vulnerabilities
    { name = "openssl", version = "*" },  # Use rustls instead
    { name = "native-tls", version = "*" },  # Use rustls-tls
    
    # Known vulnerable crates
    { name = "time", version = "<0.2.23" },  # RUSTSEC-2020-0071
    { name = "chrono", version = "<0.4.20" },  # RUSTSEC-2020-0159
    { name = "openssl", version = "*" },  # Multiple vulnerabilities

    # Unmaintained or insecure RNG
    { name = "rand", version = "<0.8" },
    { name = "uuid", version = "<1.0" },

    # Memory safety issues
    { name = "crossbeam-epoch", version = "<0.9.8" },

    # Supply chain compromise risks
    { name = "event-stream", version = "*" },  # Historical malware
    { name = "eslint-scope", version = "*" },  # Historical compromise
]

skip = [
    # Skip specific crates that may have false positives
    # Example: { name = "winapi", version = "*" },  # Windows-specific, not used in production
]

skip-tree = [
    # Skip entire dependency trees
    # Example: { name = "windows-sys", version = "*" },
]

[sources]
# Source repository restrictions for supply chain security
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = [
    "https://github.com/rust-lang/",
    "https://github.com/tokio-rs/",
    "https://github.com/serde-rs/",
    "https://github.com/rustsec/",
]

[sources.allow-org]
# Allow specific GitHub organizations
github = [
    "rust-lang",
    "tokio-rs",
    "serde-rs",
    "rustsec",
    "rustls",
    "RustCrypto",
    "hyperium",
    "tower-rs",
    "axum-rs",
]
