# cargo-deny configuration: licenses, advisories, bans, sources

[graph]
all-features = true
no-default-features = false

[advisories]
# db-path = "~/.cargo/advisory-db"
yanked = "warn"
ignore = [
    "RUSTSEC-2024-0370", # proc-macro-error unmaintained - used by utoipa
]

[licenses]
confidence-threshold = 0.8
allow = [
    "Apache-2.0",
    "MIT",
    "BSD-3-Clause",
    "BSD-2-Clause",
    "ISC",
    "Unicode-3.0",
    "MPL-2.0",
    "Zlib",
    "OpenSSL",
    "MIT-0",
]
exceptions = []

[bans]
multiple-versions = "warn"
wildcards = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
