# Modern cargo-deny configuration
# Updated to latest format for dependency security

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]
all-features = true

[licenses]
# Only allow business-friendly licenses
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause", 
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Unlicense",
    "BSL-1.0",
]

confidence-threshold = 0.8

[bans]
# Banned packages with security issues
deny = [
    { name = "time", version = "=0.1.0" }, # Unsound API
]

# Allow multiple versions for compatibility
skip = [
    { name = "thiserror", version = "*" },
    { name = "thiserror-impl", version = "*" },
    { name = "tower", version = "*" },
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/RustSec/advisory-db"]
yanked = "deny"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [
    "https://github.com/rust-lang/crates.io-index",
    "sparse+https://index.crates.io/",
]

[sources.allow-org]
github = [
    "rust-lang",
    "tokio-rs", 
    "serde-rs",
    "hyperium",
    "RustCrypto",
]