[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "aarch64-apple-darwin" },
]
all-features = false

[licenses]
unlicensed = "deny"
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception", 
    "MIT",
    "ISC",
    "Unicode-DFS-2016",
    "OpenSSL",
    "BSD-2-Clause",
    "BSD-3-Clause",
]
deny = [
    "GPL-2.0",
    "GPL-3.0", 
    "AGPL-1.0",
    "AGPL-3.0",
    "LGPL-2.0",
    "LGPL-2.1",
    "LGPL-3.0",
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
deny = [
    # Deny old versions of crypto libraries with known vulnerabilities
    { name = "openssl", version = "<0.10" },
    { name = "ring", version = "<0.16" },
    { name = "rustls", version = "<0.20" },
    
    # Deny vulnerable time library versions
    { name = "time", version = "<0.2.23" },
    { name = "chrono", version = "<0.4.20" },
    
    # Deny vulnerable serialization libraries
    { name = "serde_yaml", version = "<0.8.21" },
    { name = "toml", version = "<0.5.7" },
    
    # Deny vulnerable HTTP libraries
    { name = "hyper", version = "<0.14.12" },
    { name = "reqwest", version = "<0.11.6" },
    
    # Deny vulnerable regex library
    { name = "regex", version = "<1.5.5" },
    
    # Deny other known vulnerable crates
    { name = "smallvec", version = "<1.6.1" },
    { name = "tokio", version = "<1.8.4" },
    { name = "thread_local", version = "<1.1.4" },
]

[advisories]
version = 2
vulnerability = "deny"
unmaintained = "warn"
unsound = "warn"
yanked = "deny"
notice = "warn"
ignore = [
    # Add specific advisory IDs here if needed after review
    # Example: "RUSTSEC-2020-0001",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []