# Simplified cargo-deny configuration for supply chain security
[graph]
targets = [
    "x86_64-unknown-linux-gnu",
    "x86_64-unknown-linux-musl",
    "aarch64-unknown-linux-gnu",
]

[advisories]
# Ignore specific advisories with justification
ignore = [
    # RSA vulnerability in MySQL connector - not directly exploitable in our usage
    # We only use PostgreSQL and SQLite, MySQL support will be removed in future version
    "RUSTSEC-2023-0071", # RSA Marvin Attack - only affects MySQL connector we don't use
    # Unmaintained packages - acceptable for dev dependencies, monitoring for replacements
    "RUSTSEC-2024-0436", # paste - unmaintained, used in ML dependencies
    "RUSTSEC-2024-0370", # proc-macro-error - unmaintained, used in OpenAPI generation
]

[licenses]
# Allow common open source licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
    "0BSD",
    "Zlib",
    "MPL-2.0",
]

[bans]
# Deny multiple versions of same crate
multiple-versions = "warn"
wildcards = "allow"