# Modern cargo-deny configuration with strict security policies
# Updated to remove all ignored vulnerabilities and enforce security

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]
all-features = true

[licenses]
# Only allow business-friendly licenses
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause", 
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Unlicense",
    "BSL-1.0",
    "Zlib",
    "0BSD",
    "CDLA-Permissive-2.0",
]

confidence-threshold = 0.8

[bans]
multiple-versions = "warn"  # Change from deny to warn for better workflow
# Banned packages with security issues
deny = [
    { name = "time", version = "=0.1.0" }, # Unsound API
    { name = "openssl", version = "*" },   # Prefer ring/rustls for better security
    { name = "native-tls", version = "*" }, # Prefer rustls
    { name = "chrono", version = "<0.4.20" }, # Old versions have vulnerabilities
    { name = "pprof2", version = "*" },    # RUSTSEC-2024-0408 memory safety issue
    { name = "trust-dns-resolver", version = "*" }, # Deprecated, use hickory-dns
    { name = "mysql", version = "*" },     # Explicitly deny MySQL
    { name = "mysql_async", version = "*" },
    { name = "mysql_common", version = "*" },
]

# Allow multiple versions only for essential compatibility
skip = [
    { name = "thiserror", version = "*" },
    { name = "thiserror-impl", version = "*" },
    { name = "tower", version = "*" },
    { name = "syn", version = "*" }, # Common in proc macros
    { name = "axum", version = "*" }, # Different versions for different dependencies
    { name = "axum-core", version = "*" },
    { name = "base64", version = "*" }, # Common version conflicts
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/RustSec/advisory-db"]
yanked = "deny"

# Security vulnerabilities - all must be addressed
# No vulnerabilities are ignored - all must be fixed
ignore = []

# Note: severity-threshold has been deprecated, use individual advisory settings instead

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [
    "https://github.com/rust-lang/crates.io-index",
    "https://index.crates.io/",
]

[sources.allow-org]
github = [
    "rust-lang",
    "tokio-rs", 
    "serde-rs",
    "hyperium",
    "RustCrypto",
    "rustls",
]

# SQLx security constraints - ensure only approved features are used
[[bans.features]]
name = "sqlx"
allow = [
    "postgres",
    "sqlite", 
    "chrono",
    "uuid",
    "migrate",
    "macros",
    "runtime-tokio-rustls",  # Only allow rustls, not native-tls
]
deny = [
    "mysql",                    # MySQL support disabled due to RUSTSEC-2023-0071
    "mssql",                    # Limit database support to PostgreSQL and SQLite only
    "runtime-tokio-native-tls", # Force rustls for better security
    "runtime-async-std-native-tls",
    "tls-native-tls",
    "_unstable-all-types",      # Deny unstable features in production
]
exact = true

# Tokio security constraints
[[bans.features]]
name = "tokio"
allow = ["full", "macros", "rt", "rt-multi-thread", "net", "fs", "io-util", "time", "sync", "signal"]
deny = ["test-util"]  # Prevent test utilities in production