# Modern cargo-deny configuration with strict security policies
# Updated to remove all ignored vulnerabilities and enforce security

[graph]
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-apple-darwin" },
    { triple = "aarch64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]
all-features = true

[licenses]
# Only allow business-friendly licenses
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause", 
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Unlicense",
    "BSL-1.0",
    "Zlib",
    "0BSD",
    "CDLA-Permissive-2.0",
]

confidence-threshold = 0.8

[bans]
# Banned packages with security issues
deny = [
    { name = "time", version = "=0.1.0" }, # Unsound API
    { name = "rsa", version = "*" },       # RUSTSEC-2023-0071 Marvin attack vulnerability
    { name = "openssl", version = "*" },   # Prefer ring/rustls for better security
    { name = "native-tls", version = "*" }, # Prefer rustls
    { name = "chrono", version = "<0.4.20" }, # Old versions have vulnerabilities
    { name = "pprof2", version = "*" },    # RUSTSEC-2024-0408 memory safety issue
    { name = "trust-dns-resolver", version = "*" }, # Deprecated, use hickory-dns
]

# Allow multiple versions for compatibility during migration
skip = [
    { name = "thiserror", version = "*" },
    { name = "thiserror-impl", version = "*" },
    { name = "tower", version = "*" },
    { name = "syn", version = "*" }, # Common in proc macros
    { name = "quote", version = "*" }, # Common in proc macros
]

[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/RustSec/advisory-db"]
yanked = "deny"

# REMOVED ALL IGNORED VULNERABILITIES - FIX THEM INSTEAD
# All security vulnerabilities must be addressed, not ignored
ignore = []

# Note: severity-threshold has been deprecated, use individual advisory settings instead

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = [
    "https://github.com/rust-lang/crates.io-index",
    "https://index.crates.io/",
]

[sources.allow-org]
github = [
    "rust-lang",
    "tokio-rs", 
    "serde-rs",
    "hyperium",
    "RustCrypto",
    "rustls",
]