version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  auth-service:
    build:
      context: ./auth-service
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=debug,auth_service=trace
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=development-jwt-secret-change-in-production-this-is-not-secure-enough
      - CLIENT_CREDENTIALS=dev_client:dev_secret_123456789;admin_client:admin_secret_987654321
      - ALLOWED_SCOPES=read,write,admin
      - RATE_LIMIT_REQUESTS_PER_MINUTE=120
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  policy-service:
    build:
      context: ./policy-service
      dockerfile: Dockerfile
    container_name: policy-service
    ports:
      - "8081:8080"
    environment:
      - RUST_LOG=debug,policy_service=trace
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  redis_data:
    driver: local

networks:
  default:
    name: rust-security-network
