[toolchain]
channel = "stable"  # Use latest stable
components = ["rustfmt", "clippy", "rust-src", "rust-analyzer", "llvm-tools-preview"]
targets = ["x86_64-unknown-linux-gnu", "x86_64-apple-darwin", "aarch64-apple-darwin"]
profile = "default"
