apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: auth-service-secrets
  namespace: rust-security
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: auth-service-secrets
    creationPolicy: Owner
  data:
  - secretKey: jwt-secret
    remoteRef:
      key: auth-service/jwt
      property: secret
  - secretKey: database-url
    remoteRef:
      key: auth-service/database
      property: url
  - secretKey: redis-url
    remoteRef:
      key: auth-service/redis
      property: url
  - secretKey: encryption-key
    remoteRef:
      key: auth-service/encryption
      property: key

---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: rust-security
spec:
  provider:
    vault:
      server: "https://vault.internal.company.com"
      path: "secret"
      version: "v2"
      auth:
        kubernetes:
          mountPath: "kubernetes"
          role: "auth-service"
          serviceAccountRef:
            name: "auth-service"

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: rust-security
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "auth-service"