[package]
name = "auth-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "sync"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }
uuid = { version = "1", features = ["v4", "serde"] }
thiserror = "1"
http = "1"
hyper = { version = "1", features = ["full"] }
tower = { version = "0.5", features = ["limit"] }
tower-http = { version = "0.6", features = ["trace", "request-id", "limit", "cors"] }
anyhow = "1"
dotenvy = "0.15"
redis = { version = "0.32", features = ["tokio-comp", "aio", "connection-manager"] }
utoipa = { version = "4", features = ["axum_extras", "uuid"] }
# Swagger UI is optional; enable with `--features docs`
utoipa-swagger-ui = { version = "6", features = ["axum"], optional = true }
# Security enhancements
validator = { version = "0.20", features = ["derive"] }
secrecy = "0.10"
argon2 = "0.5"
jsonwebtoken = "9"
# Replaced rsa with ring for better security (fixes RUSTSEC-2023-0071)
ring = "0.17"
rsa = { version = "0.9" }
chrono = { version = "0.4", features = ["serde"] }
envy = "0.4"
hmac = "0.12"
sha1 = "0.10"
data-encoding = "2.6"
sha2 = "0.10"
# TLS/HTTPS support
axum-server = { version = "0.7", features = ["tls-rustls"] }
rcgen = "0.13"
# Secret management
async-trait = "0.1"
aes-gcm = "0.10"
rand = "0.8"
once_cell = "1"
base64 = "0.21"
# Updated to fix protobuf vulnerability RUSTSEC-2024-0437
prometheus = "0.14"
getrandom = "0.2"
urlencoding = "2.1"
url = "2.5"
reqwest = { version = "0.12", features = ["json", "rustls-tls"] }
regex = "1"
# OpenTelemetry for distributed tracing
opentelemetry = { version = "0.21", optional = true }
opentelemetry-jaeger = { version = "0.20", optional = true }
tracing-opentelemetry = { version = "0.22", optional = true }
opentelemetry_sdk = { version = "0.21", features = ["rt-tokio"], optional = true }
# Performance and benchmarking
criterion = { version = "0.5", features = ["html_reports"], optional = true }

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
serde_json = "1"

[features]
default = []
docs = ["utoipa-swagger-ui"]
vault = ["vaultrs"]
aws = ["aws-config", "aws-sdk-secretsmanager"]
tracing = ["opentelemetry", "opentelemetry-jaeger", "tracing-opentelemetry", "opentelemetry_sdk"]
benchmarks = ["criterion"]

[[bench]]
name = "performance_suite"
harness = false
required-features = ["benchmarks"]

[dependencies.vaultrs]
version = "0.7"
optional = true

[dependencies.aws-config]
version = "1"
optional = true

[dependencies.aws-sdk-secretsmanager]
version = "1"
optional = true

[lib]
name = "auth_service"
path = "src/lib.rs"

[[bin]]
name = "auth-service"
path = "src/main.rs"
