[package]
name = "auth-service"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.7", features = ["macros"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "signal", "sync"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }
uuid = { version = "1", features = ["v4", "serde"] }
thiserror = "1"
http = "1"
hyper = { version = "1", features = ["full"] }
tower = { version = "0.5", features = ["limit"] }
tower-http = { version = "0.6", features = ["trace", "request-id", "limit", "cors"] }
anyhow = "1"
dotenvy = "0.15"
redis = { version = "0.32", features = ["tokio-comp", "aio", "connection-manager"] }
utoipa = { version = "4", features = ["axum_extras", "uuid"] }
# Swagger UI is optional; enable with `--features docs`
utoipa-swagger-ui = { version = "6", features = ["axum"], optional = true }
# Security enhancements
validator = { version = "0.20", features = ["derive"] }
secrecy = "0.10"
argon2 = "0.5"
jsonwebtoken = "9"
# Using jsonwebtoken for RSA operations (more secure than direct RSA usage)
# Removed vulnerable rsa crate (RUSTSEC-2023-0071)
chrono = { version = "0.4", features = ["serde"] }
envy = "0.4"
hmac = "0.12"
sha1 = "0.10"
data-encoding = "2.6"
sha2 = "0.10"
# TLS/HTTPS support
axum-server = { version = "0.7", features = ["tls-rustls"] }
rcgen = "0.13"
# Secret management
async-trait = "0.1"
aes-gcm = "0.10"
chacha20poly1305 = "0.10"
hex = "0.4"
rand = "0.8"
once_cell = "1"
base64 = "0.21"
# SOAR optional dependencies
sqlx = { version = "0.8", features = ["runtime-tokio-rustls", "postgres", "uuid", "chrono", "json"], optional = true }
handlebars = { version = "6.1", optional = true }
lettre = { version = "0.11", features = ["smtp-transport", "pool", "hostname", "builder", "rustls-tls"], default-features = false, optional = true }
tera = { version = "1.20", optional = true }
tempfile = { version = "3.10", optional = true }
walkdir = { version = "2.5", optional = true }
# Updated to fix protobuf vulnerability RUSTSEC-2024-0437
prometheus = "0.14"
getrandom = "0.2"
urlencoding = "2.1"
url = "2.5"
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
regex = "1"
# High-performance rate limiting
dashmap = "6.1"
num_cpus = "1.16"
# OpenTelemetry for distributed tracing
opentelemetry = { version = "0.21", optional = true }
opentelemetry-jaeger = { version = "0.20", optional = true }
tracing-opentelemetry = { version = "0.22", optional = true }
opentelemetry_sdk = { version = "0.21", features = ["rt-tokio"], optional = true }
# Performance and benchmarking
criterion = { version = "0.5", features = ["html_reports"], optional = true }
# SIMD and hardware acceleration
simd = { version = "0.2", optional = true }
ring = "0.17"
aes = "0.8"
rayon = "1.8"
# Memory optimization
mimalloc = { version = "0.1", optional = true }
jemalloc = { version = "0.3", optional = true }
# High-performance async runtime
tokio-metrics = "0.3"
# Connection pooling optimization
bb8 = "0.8"
bb8-redis = "0.24"
deadpool = "0.12"
deadpool-redis = "0.14"
# Optimized serialization
rmp-serde = "1.1"
bincode = "1.3"
# Metrics and profiling
pprof = { version = "0.13", features = ["criterion", "flamegraph"], optional = true }

# Threat Hunting and ML Dependencies
# Machine Learning and Data Analysis
smartcore = { version = "0.3", features = ["serde"], optional = true }
candle-core = { version = "0.8", optional = true }
candle-nn = { version = "0.8", optional = true }
candle-transformers = { version = "0.8", optional = true }
ndarray = { version = "0.16", features = ["serde"], optional = true }
nalgebra = { version = "0.32", features = ["serde"], optional = true }
# Graph analysis for attack pattern detection
petgraph = { version = "0.6", features = ["serde"], optional = true }
# Time series analysis
tsc = { version = "0.1", optional = true }
# Statistics and analytics
statrs = { version = "0.17", optional = true }
# Advanced collections for threat correlation
indexmap = { version = "2.0", features = ["serde"], optional = true }
# Async channels and queues
flume = { version = "0.11", optional = true }
crossbeam = { version = "0.8", optional = true }
# Geospatial analysis for location anomalies
geo = { version = "0.28", features = ["serde"], optional = true }
geoutils = { version = "0.5", optional = true }
# Enhanced time handling
time = { version = "0.3", features = ["parsing", "formatting", "serde"], optional = true }
# Memory-mapped files for large datasets
memmap2 = { version = "0.9", optional = true }
# Compression for data storage
lz4_flex = { version = "0.11", optional = true }
# IP address analysis
ipnet = { version = "2.9", optional = true }
# Enhanced string processing for log parsing
fancy-regex = { version = "0.13", optional = true }
aho-corasick = { version = "1.1", optional = true }
# Bloom filters for efficient lookups
bloomfilter = { version = "1.0", optional = true }
# Probabilistic data structures
probabilistic-collections = { version = "0.7", optional = true }
# Lazy static for static variables
lazy_static = "1.4"

# Post-Quantum Cryptography dependencies
pqcrypto-kyber = { version = "0.8", optional = true }
pqcrypto-dilithium = { version = "0.4", optional = true }
# Hybrid cryptography support
p256 = { version = "0.13", optional = true }
p384 = { version = "0.13", optional = true }
ed25519-dalek = { version = "2.1", optional = true }
x25519-dalek = { version = "2.0", optional = true }
# Certificate and PKI support for post-quantum
x509-cert = { version = "0.2", optional = true }
pkcs8 = { version = "0.10", optional = true }
der = { version = "0.7", optional = true }
# Performance and security utilities
constant_time_eq = "0.3"
zeroize = "1.7"
subtle = "2.5"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
tokio = { version = "1", features = ["rt-multi-thread", "macros", "time"] }
serde_json = "1"
# Test dependencies
uuid = { version = "1", features = ["v4"] }
rand = "0.8"
base64 = "0.21"
hmac = "0.12"
sha2 = "0.10"
sha1 = "0.10"
data-encoding = "2.6"
chrono = { version = "0.4", features = ["serde"] }
url = "2.5"
urlencoding = "2.1"
# Property-based testing
proptest = "1.4"
quickcheck = "1.0"
quickcheck_macros = "1.0"
# Performance testing
tokio-test = "0.4"
# Security testing
regex = "1"
# Test utilities
tempfile = "3.10"
wiremock = "0.6"
# Fuzzing
arbitrary = { version = "1.3", features = ["derive"] }
# Coverage and benchmarking in tests
# tarpaulin = "0.30"  # Commented out - not available on crates.io

[features]
default = []
docs = ["utoipa-swagger-ui"]
vault = ["vaultrs"]
aws = ["aws-config", "aws-sdk-secretsmanager"]
tracing = ["opentelemetry", "opentelemetry-jaeger", "tracing-opentelemetry", "opentelemetry_sdk"]
benchmarks = ["criterion", "pprof"]
simd = []
mimalloc = ["dep:mimalloc"]
jemalloc = ["dep:jemalloc"]
performance = ["dep:simd", "mimalloc"]
profiling = ["pprof"]
# Post-quantum cryptography feature flags
post-quantum = ["pqcrypto-kyber", "pqcrypto-dilithium", "x509-cert", "pkcs8", "der"]
hybrid-crypto = ["post-quantum", "p256", "p384", "ed25519-dalek", "x25519-dalek"]
# Threat hunting feature flags
threat-hunting = ["smartcore", "petgraph", "ndarray", "nalgebra", "geo", "statrs", "indexmap", "flume", "crossbeam"]
ml-enhanced = ["threat-hunting", "candle-core", "candle-nn", "candle-transformers"]
advanced-analytics = ["threat-hunting", "ml-enhanced", "dep:tsc", "dep:memmap2", "dep:lz4_flex", "dep:probabilistic-collections"]
optimizations = []
soar = ["dep:sqlx", "dep:lettre", "dep:tempfile", "dep:tera", "dep:handlebars", "dep:walkdir"]

[[bench]]
name = "performance_suite"
harness = false
required-features = ["benchmarks"]

[dependencies.vaultrs]
version = "0.7"
optional = true

[dependencies.aws-config]
version = "1"
optional = true

[dependencies.aws-sdk-secretsmanager]
version = "1"
optional = true

[lib]
name = "auth_service"
path = "src/lib.rs"

[[bin]]
name = "auth-service"
path = "src/main.rs"

# (SOAR dependencies moved under [dependencies] above)

