[package]
name = "red-team-exercises"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
reqwest = { version = "0.12", features = ["json", "rustls-tls"], default-features = false }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = "1.0"
chrono = { version = "0.4", features = ["serde"] }
rand = "0.8"
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
tracing = "0.1"
tracing-subscriber = "0.3"
base64 = "0.21"
jsonwebtoken = "9.0"
sha2 = "0.10"
hmac = "0.12"
url = "2.3"
redis = "0.32"
futures = "0.3"
prometheus = "0.14"
hyper = "1.0"
# hyper-tls removed to avoid native-tls dependency
trust-dns-resolver = "0.23"
pem = "3.0"
# rsa crate removed due to RUSTSEC-2023-0071 vulnerability
x509-parser = "0.15"
pprof = { version = "0.13", features = ["criterion", "flamegraph"] }
criterion = { version = "0.5", features = ["html_reports"] }
pretty_assertions = "1.4"
colored = "2.0"
indicatif = "0.17"
tabular = "0.2"
