[build]
rustflags = [
    "-C", "target-cpu=native",
]

[target.x86_64-unknown-linux-gnu]
rustflags = [
    "-C", "link-arg=-fuse-ld=lld",
]

# macOS uses the system linker by default
[target.aarch64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native",
]

[target.x86_64-apple-darwin]
rustflags = [
    "-C", "target-cpu=native",
]
