author: Rust Security Workspace - Threat Intelligence
date: 2025/08/16
description: Detects suspicious user agent strings commonly used by malware
detection:
  condition: selection and not filter
  filter:
    cs-user-agent|contains:
    - googlebot
    - bingbot
    - slurp
  selection:
    cs-user-agent|contains:
    - wget
    - curl
    - python-requests
    - scanner
    - bot
    - crawler
falsepositives:
- Legitimate automated tools
- Monitoring systems
id: threat-intel-suspicious-ua-001
level: medium
logsource:
  category: webserver
status: experimental
tags:
- attack.defense_evasion
- attack.t1036
title: Suspicious User Agent
