# Development Configuration for Rust Security Platform
# This file contains all required configuration for successful service startup

[server]
host = "127.0.0.1"
port = 8080
bind_addr = "127.0.0.1:8080"
max_connections = 10000
request_timeout = "30s"
shutdown_timeout = "30s"

[database]
url = "sqlite::memory:"
max_connections = 32
min_connections = 5
connect_timeout = "30s"
acquire_timeout = "30s"
idle_timeout = "600s"
max_lifetime = "1800s"
test_before_acquire = true

[redis]
url = "redis://localhost:6379"
pool_size = 10
connection_timeout = "5s"
command_timeout = "2s"

[security]
bcrypt_cost = 12
password_min_length = 12
password_require_uppercase = true
password_require_lowercase = true
password_require_digit = true
password_require_special = true
max_login_attempts = 5
lockout_duration = "15m"
secure_cookies = false
csrf_protection = true

[security.argon2_params]
memory_cost = 4096
time_cost = 3
parallelism = 1
salt_length = 32
hash_length = 32

[security.cors]
# SECURITY: Use explicit origin whitelist instead of wildcards
# Add your specific frontend domains here
allowed_origins = ["http://localhost:3000", "http://localhost:8080"]
allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
allowed_headers = ["Content-Type", "Authorization", "X-Requested-With", "X-CSRF-Token"]
exposed_headers = ["X-Request-ID"]
max_age = 3600  # Reduced from 86400 (1 day) to 3600 (1 hour) for better security
# SECURITY: Only enable credentials for same-origin or trusted origins
# Consider setting to false if not needed for your application
allow_credentials = false

[jwt]
# SECURITY: Remove hardcoded secret. Set JWT_SECRET environment variable instead.
# Example: export JWT_SECRET="your-secure-randomly-generated-secret-key"
secret = "${JWT_SECRET}"
issuer = "http://localhost:8080"
audience = ["api", "web-client", "mobile-app"]
access_token_ttl = "1h"
refresh_token_ttl = "7d"
algorithm = "HS256"
key_rotation_interval = "30d"
leeway = "60s"

[oauth]
providers = []
redirect_base_url = "http://localhost:8080/auth/callback"
state_ttl = "10m"
pkce_required = true

[rate_limiting]
global_limit = 10000
global_window = "60s"
per_ip_limit = 100
per_ip_window = "60s"
per_user_limit = 1000
per_user_window = "60s"
burst_size = 10
cleanup_interval = "5m"
whitelist = []

[session]
ttl = "1h"
cookie_name = "auth_session"
cookie_secure = false
cookie_http_only = true
cookie_same_site = "Lax"
cleanup_interval = "1h"
max_sessions_per_user = 5

[monitoring]
metrics_enabled = true
metrics_path = "/metrics"
health_check_path = "/health"
tracing_enabled = true
tracing_level = "info"
jaeger_endpoint = ""
prometheus_enabled = true
log_format = "json"

[features]
mfa_enabled = true
webauthn_enabled = false
api_keys_enabled = true
oauth_enabled = true
scim_enabled = false
audit_logging_enabled = true
enhanced_security = true
post_quantum_crypto = false