[package]
name = "mvp-oauth-service"
version = "0.1.0"
edition = "2021"
description = "MVP OAuth 2.0 service with enhanced security validation"

[[bin]]
name = "mvp-oauth"
path = "src/main.rs"

[dependencies]
# Core web framework
axum = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tower = { workspace = true }
tower-http = { workspace = true, features = ["cors", "trace"] }

# Serialization
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }

# JWT and crypto
jsonwebtoken = { workspace = true }
base64 = { workspace = true }
chrono = { workspace = true, features = ["serde"] }

# Enhanced validation and policy engine
mvp-tools = { path = "../mvp-tools" }

# Logging and tracing
tracing = { workspace = true }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

# Error handling
anyhow = { workspace = true }

# Configuration
uuid = { workspace = true, features = ["v4"] }
