[package]
name = "common"
version = "0.1.0"
edition = "2021"
description = "Common types and utilities for the rust-security workspace"

[lints]
workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
thiserror = { workspace = true }
anyhow = { workspace = true }
url = { workspace = true }
regex = { workspace = true }
rand = { workspace = true }
async-trait = { workspace = true }

[features]
default = []