[package]
name = "runtime-security-monitor"
version = "0.1.0"
edition = "2021"
description = "Runtime security monitoring and threat detection"

[dependencies]
tokio = { version = "1.47", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
prometheus = "0.14"
regex = "1.11"
anyhow = "1.0"
thiserror = "2.0"
chrono = { version = "0.4", features = ["serde"] }
dashmap = "6.1"
once_cell = "1.21"

# Security monitoring
notify = "6.1"
sysinfo = "0.33"
procfs = "0.19"
nix = { version = "0.30", features = ["process", "signal", "user"] }

# Network monitoring
pnet = "0.36"
pcap = "2.4"
dns-lookup = "2.0"

# Anomaly detection
ndarray = "0.16"
statrs = "0.17"

# Alert management
reqwest = { version = "0.12", features = ["json"] }
lettre = { version = "0.11", default-features = false, features = ["smtp-transport", "hostname", "builder", "rustls-tls"] }

[dev-dependencies]
tempfile = "3.21"
mockito = "1.6"