[package]
name = "runtime-security-monitor"
version = "0.1.0"
edition = "2021"
description = "Runtime security monitoring and threat detection"

[dependencies]
tokio = { version = "1.47", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
serde = { version = "1.0", features = ["derive"] }
prometheus = "0.14"
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
dashmap = "6.1"
once_cell = "1.21"

[dev-dependencies]
tempfile = "3.21"
mockito = "1.6"
