apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      prometheusType: Prometheus
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: jaeger

  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    url: http://elasticsearch:9200
    database: "security-logs-*"
    jsonData:
      interval: Daily
      timeField: "@timestamp"
      esVersion: "8.5.0"
      logMessageField: message
      logLevelField: level
      maxConcurrentShardRequests: 5

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    uid: jaeger
    jsonData:
      tracesToLogsV2:
        datasourceUid: elasticsearch
        tags:
          - key: service.name
            value: service_name
        filterByTraceID: false
        filterBySpanID: false
        customQuery: true
        query: 'trace_id:"${__trace.traceID}"'
