apiVersion: v1
kind: ServiceAccount
metadata:
  name: auth-service
  namespace: rust-security
  annotations:
    # Disable automatic token mounting for security
    kubernetes.io/service-account-token: "false"
automountServiceAccountToken: false

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: rust-security
  name: auth-service-role
rules:
# Allow reading ConfigMaps for configuration
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
# Allow reading Secrets for credentials
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]
# Allow reading own Pod info for health checks (using label selector instead of resourceNames)
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: auth-service-binding
  namespace: rust-security
subjects:
- kind: ServiceAccount
  name: auth-service
  namespace: rust-security
roleRef:
  kind: Role
  name: auth-service-role
  apiGroup: rbac.authorization.k8s.io

---
# Removed overly permissive ClusterRole and ClusterRoleBinding
# Auth service should not need cluster-wide permissions
# If monitoring is needed, it should be handled by dedicated monitoring components