apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rust-security-auth-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: rust-security
    app.kubernetes.io/component: auth-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: rust-security
  source:
    repoURL: https://github.com/your-org/rust-security
    targetRevision: HEAD
    path: helm/auth-service
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
      parameters:
        - name: image.tag
          value: "latest"
        - name: replicaCount
          value: "3"
  destination:
    server: https://kubernetes.default.svc
    namespace: rust-security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rust-security-policy-service
  namespace: argocd
  labels:
    app.kubernetes.io/name: rust-security
    app.kubernetes.io/component: policy-service
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: rust-security
  source:
    repoURL: https://github.com/your-org/rust-security
    targetRevision: HEAD
    path: helm/policy-service
    helm:
      valueFiles:
        - values.yaml
        - values-production.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: rust-security
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: rust-security
  namespace: argocd
  labels:
    app.kubernetes.io/name: rust-security
spec:
  description: Rust Security Workspace Project
  sourceRepos:
    - https://github.com/your-org/rust-security
    - https://charts.bitnami.com/bitnami
  destinations:
    - namespace: rust-security
      server: https://kubernetes.default.svc
    - namespace: rust-security-staging
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
    - group: rbac.authorization.k8s.io
      kind: ClusterRole
    - group: rbac.authorization.k8s.io
      kind: ClusterRoleBinding
  namespaceResourceWhitelist:
    - group: ""
      kind: ConfigMap
    - group: ""
      kind: Secret
    - group: ""
      kind: Service
    - group: ""
      kind: ServiceAccount
    - group: apps
      kind: Deployment
    - group: apps
      kind: ReplicaSet
    - group: networking.k8s.io
      kind: Ingress
    - group: networking.k8s.io
      kind: NetworkPolicy
    - group: policy
      kind: PodDisruptionBudget
    - group: autoscaling
      kind: HorizontalPodAutoscaler
    - group: monitoring.coreos.com
      kind: ServiceMonitor
  roles:
    - name: admin
      description: Admin access to rust-security project
      policies:
        - p, proj:rust-security:admin, applications, *, rust-security/*, allow
        - p, proj:rust-security:admin, repositories, *, *, allow
      groups:
        - rust-security:admins
    - name: developer
      description: Developer access to rust-security project
      policies:
        - p, proj:rust-security:developer, applications, get, rust-security/*, allow
        - p, proj:rust-security:developer, applications, sync, rust-security/*, allow
      groups:
        - rust-security:developers
  syncWindows:
    - kind: allow
      schedule: "0 9-17 * * 1-5"  # Business hours, weekdays only
      duration: 8h
      applications:
        - "*"
      manualSync: true
    - kind: deny
      schedule: "0 0-8,18-23 * * *"  # Outside business hours
      duration: 10h
      applications:
        - "*"
      manualSync: false
