name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: stable

jobs:
  build_and_test:
    name: Build & Test (Rust ${{ matrix.rust }} on ${{ matrix.os }})
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable, nightly]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: rustfmt, clippy

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ matrix.os }}-${{ matrix.rust }}

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy (strict)
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings -D clippy::all -D clippy::pedantic

      - name: Build (Debug)
        run: cargo build --workspace --verbose

      - name: Run unit tests
        run: cargo test --workspace --verbose

      - name: Build (Release)
        run: cargo build --workspace --release --verbose

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries-${{ matrix.os }}-${{ matrix.rust }}
          path: |
            target/release/auth-service
            target/release/policy-service
        if: matrix.os == 'ubuntu-latest' && matrix.rust == 'stable'

      - name: Generate coverage report
        if: matrix.rust == 'stable' && matrix.os == 'ubuntu-latest'
        run: |
          cargo install cargo-llvm-cov --locked
          cargo llvm-cov --workspace --all-features --lcov --output-path lcov.info

      - name: Upload coverage to Codecov
        if: matrix.rust == 'stable' && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v3
        with:
          file: lcov.info
          fail_ci_if_error: false

      - name: Check coverage baseline
        if: matrix.rust == 'stable' && matrix.os == 'ubuntu-latest'
        run: |
          BASELINE_COVERAGE=70
          COVERAGE=$(cargo llvm-cov --workspace --all-features --summary-only | grep -E "^TOTAL" | awk '{print $10}' | sed 's/%//')
          echo "Current coverage: ${COVERAGE}%"
          echo "Baseline: ${BASELINE_COVERAGE}%"
          if (( $(echo "$COVERAGE >= $BASELINE_COVERAGE" | bc -l) )); then
            echo "✅ Coverage meets baseline"
          else
            echo "❌ Coverage below baseline"
            exit 1
          fi

  security:
    name: Security Checks
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_VERSION }}

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install security tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit,cargo-deny,cargo-outdated

      - name: Audit dependencies
        run: cargo audit --deny warnings

      - name: Check dependency licenses and policies
        run: cargo deny check

      - name: Check for outdated dependencies
        # Fails the build if outdated dependencies are found.
        # To fix, run 'cargo update' locally and commit the changes.
        run: cargo outdated --workspace --exit-code 1

      - name: Filesystem vulnerability scan (Trivy)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-fs-results.sarif'

      - name: Upload Trivy FS scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        if: always()
        with:
          sarif_file: 'trivy-fs-results.sarif'

  integration_test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-binaries-ubuntu-latest-stable
          path: target/release

      - name: Make binaries executable
        run: chmod +x target/release/auth-service target/release/policy-service

      - name: Start services
        run: |
          ./target/release/auth-service &
          ./target/release/policy-service &

      - name: Wait for services to be healthy
        run: |
          ./scripts/validation/wait-for-service.sh http://localhost:8080/health
          ./scripts/validation/wait-for-service.sh http://localhost:8081/health

      - name: Run integration tests
        run: cargo test --test '*integration*' --all-features --verbose

      - name: Cleanup services
        if: always()
        run: pkill -f "auth-service|policy-service" || true

  docker:
    name: Docker Build & Scan
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build Docker images
        run: |
          docker build -f auth-service/Dockerfile.prod -t auth-service:test .
          docker build -f policy-service/Dockerfile -t policy-service:test .

      - name: Scan Docker images with Trivy
        run: |
          docker run --rm --pull=always \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/Library/Caches:/root/.cache/ \
            aquasec/trivy:latest image --exit-code 1 --severity HIGH,CRITICAL auth-service:test
          docker run --rm --pull=always \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v $HOME/Library/Caches:/root/.cache/ \
            aquasec/trivy:latest image --exit-code 1 --severity HIGH,CRITICAL policy-service:test

  performance_test:
    name: Performance Tests
    runs-on: ubuntu-latest
    needs: build_and_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release-binaries-ubuntu-latest-stable
          path: target/release

      - name: Make binaries executable
        run: chmod +x target/release/auth-service target/release/policy-service

      - name: Install load testing tools
        run: sudo apt-get update && sudo apt-get install -y apache2-utils

      - name: Start services
        run: |
          ./target/release/auth-service &
          ./target/release/policy-service &

      - name: Wait for services to be healthy
        run: |
          ./scripts/validation/wait-for-service.sh http://localhost:8080/health
          ./scripts/validation/wait-for-service.sh http://localhost:8081/health

      - name: Run performance tests
        run: |
          chmod +x scripts/testing/load_test.sh
          ./scripts/testing/load_test.sh http://localhost:8080 5 50

      - name: Cleanup services
        if: always()
        run: pkill -f "auth-service|policy-service" || true

  duplicate_code_analysis:
    name: Duplicate Code Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run jscpd
        run: |
          npx jscpd@3.5.10 --config .jscpd.json
