name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          override: true

      - name: Cache cargo
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-audit and cargo-deny
        run: |
          cargo install cargo-audit --locked
          cargo install cargo-deny --locked

      - name: Format check
        run: cargo fmt --all -- --check

      - name: Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

      - name: Tests
        run: cargo test --all --all-features --verbose

      - name: Security audit
        run: cargo audit --deny warnings

      - name: License/dep policy (cargo-deny)
        run: cargo deny check --all-features


