name: Clean Code Standards

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  clean-code:
    name: Clean Code Checks
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install Rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt, clippy
        
    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Check formatting
      run: cargo fmt --all -- --check
      
    - name: Run clippy
      run: cargo clippy --workspace --all-features -- -D warnings
      
    - name: Run tests
      run: cargo test --workspace --all-features
      
    - name: Check documentation
      run: cargo doc --workspace --all-features --no-deps
      
    - name: Security audit
      run: |
        cargo install cargo-audit
        cargo audit
        
    - name: Run clean code enforcement
      run: ./scripts/enforce-clean-code.sh
