name: PR Label Dispatcher

on:
  pull_request:
    types: [labeled]

permissions:
  contents: read
  issues: write
  pull-requests: write

concurrency:
  group: pr-label-dispatcher-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Post slash-command for matching labels
        uses: actions/github-script@v7
        with:
          script: |
            const label = context.payload.label?.name || '';
            const number = context.payload.pull_request.number;
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const map = new Map([
              ['security-scan', '/security-scan full'],
              ['performance-scan', '/performance-scan'],
              ['compliance-scan', '/compliance-scan'],
              ['api-validate', '/api-validate'],
              ['frontend-validate', '/frontend-validate'],
              ['image-scan', '/image-scan'],
            ]);

            if (map.has(label)) {
              const body = map.get(label);
              await github.rest.issues.createComment({ owner, repo, issue_number: number, body });
              core.info(`Posted command '${body}' for label '${label}'`);
            } else {
              core.info(`No command mapped for label '${label}'`);
            }

