name: Rust CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read

jobs:
  rust-ci:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache cargo registry
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Show rustc/cargo versions
        run: |
          rustc -Vv
          cargo -V

      - name: Build (workspace)
        run: cargo build --workspace --all-features --locked

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Clippy (deny warnings)
        continue-on-error: true
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings -W clippy::perf -W clippy::suspicious

      - name: Run tests (workspace)
        continue-on-error: true
        env:
          TEST_MODE: "1"
        run: cargo test --workspace --all-features --verbose -- --nocapture

      - name: Install cargo-audit
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-audit

      - name: Run cargo audit
        run: cargo audit --deny warnings || true

      - name: Install cargo-deny
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny

      - name: Run cargo deny
        run: cargo deny check --all-features || true
